export const POSTREQREGISTER = "POSTREQREGISTER"
export const POSTSUCCESSREGISTER = "POSTSUCCESSREGISTER"
export const POSTFAILREGISTER = "POSTFAILREGISTER"

export const GETLOGINREQ = "GETLOGINREQ"
export const GETLOGINSUCCESS = "GETLOGINSUCCESS"
export const GETLOGINFAIL = "GETLOGINFAIL"

